#adapted from example in docker documentation
version: '3'

services:
  web:
    restart: always
    build: .
    volumes:
       - .:/code
    # ports:
       # - 8000:8000
    expose:
      - "8000"
    command: python /code/climbproject/manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - "6379"

  nginx:
    restart: always
    build: ./climbproject/nginx/
    depends_on:
      - web
    ports:
      - "80:80"
    #  - "443:443"
#     volumes:
#        - ./code/static:/static
    links:
      - web:web
