# Generated by Django 2.1.2 on 2018-11-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbapp', '0004_auto_20181108_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbmodel',
            name='difficulty',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
