# Generated by Django 2.1.2 on 2018-11-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbapp', '0005_climbmodel_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbmodel',
            name='in_or_out',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
