# Generated by Django 2.1.2 on 2018-11-19 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbapp', '0006_climbmodel_in_or_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climbmodel',
            name='in_or_out',
        ),
    ]
