# Generated by Django 2.1.2 on 2018-12-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbapp', '0008_climbmodel_outdoor_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbmodel',
            name='climb_notes',
            field=models.CharField(default=1, max_length=240),
            preserve_default=False,
        ),
    ]
